### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by antopilo** [cpichard/usdassimp#1]
Hello,

I am currently in the process of trying to make this plugin work for USD on windows.

Is there a way I can reach out?

Thank you

**Comment by cpichard** [comment]
Hi @antopilo, 
sure, you can contact me by mail: cpicharc.github(at)gmail
but also you can start an issue stating your problem.
I haven't compiled usdassimp on windows yet, I can try this weekend.
Best,
C

**Comment by antopilo** [comment]
Perfect,

The issue I am currently having after building the plugin and installing it in the proper directory for USD to detect it, is that after doing usdcat example1.ply

I get : `Failed to open ".\\example1.ply" - Cannot determine file format for @example1.ply@`

Now, the issue isnt because usd doesnt detect my dll because if I remove it from the plugins folder, it says that it cannot find the dll. So clearly the plugin is being detected.

I am not sure how to debug the dll with usdcat.

Thank you

**Comment by cpichard** [comment]
Hi @antopilo ,

This might happen if plugInfo.json in plugin/usd/usdAssimp/resources/ contains incorrect information: most likely incorrect library name or path. Or may be it is simply not read, depending on where you install this plugin, there should be a plugInfo.json above in the hierarchy that will look like:
```
{
    "Includes": [ "*/resources/" ]
} 
```
forcing the resources subfolders to be read.

The plugInfo.json in plugin/usd/usdAssimp/resources/ will declare this plugin as a fileformat plugin handling the ply extensions

Hope that helps,

C
